<?php
/**
 * Plugin Name:       TOC Widget
 * Plugin URI:        https://iglin.dev
 * Description:       This essential utility plugin is designed to enhance post readability and navigation by automatically generating a dynamic Table of Contents (TOC) for blog posts.
 * Version:           1.0.0
 * Author:            Roman Iglin
 * Author URI:        https://iglin.dev
 * Text Domain:       toc
 * Domain Path:       /languages
 *
 * Generated by WordPress Plugin Generator v1.1.1 (wordpressplugingenerator.com)
 *
 */

// Prevent to access the file from outside of WordPress
if(!defined('ABSPATH')) {
	exit;
}
if(!function_exists('wp_get_current_user')) {
	include(ABSPATH . 'wp-includes/pluggable.php');
}

class toc_Loader {
	public $config = [
		'name' => 'TOC Widget',
		'version' => '1.0.0',
		'textDomain' => 'toc',
		'textDomainPath' => 'languages',
		'slug' => 'toc-widget',
		'prefix' => 'toc',
		'prefixSeparator' => '_',
	];
	
	//
	public function __construct() {
		self::init();

		self::start();
	}

	/**
	 * Initialize the plugin
	 */
	private function init() {
	}

	
	/**
	 * Deactivates the plugin due to the missing requirements.
	 */
	public function deactivate() {
		if(current_user_can('activate_plugins') && is_plugin_active(plugin_basename(__FILE__))) {
			deactivate_plugins(plugin_basename(__FILE__));
	
			// Hide the default "Plugin activated" notice
			if(isset($_GET['activate'])) {
				unset($_GET['activate']);
			}
		}
	}

	/**
	 * Starting the plugin.
	 */
	public function start() {
		require_once plugin_dir_path(__FILE__) . 'classes/plugin.php';
		$plugin = new toc_Plugin($this->config);

		register_activation_hook(__FILE__, [&$plugin, 'activate']);
		register_deactivation_hook(__FILE__, [&$plugin, 'deactivate']);
	}
}

$toc = new toc_Loader();
